version: "3.8"

services:
  db:
    image: mysql
    hostname: mysql
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
  web-api-employees:
    image: web-api-employees
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db

